### ISSUE TITLE
Colophon?

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-m3d#2]
> As with all M3AAWG documents that we publish, please check the M3AAWG website (www.m3aawg.org) for updates to this paper.
> © 2017 copyright by the Messaging, Malware and Mobile Anti-Abuse Working Group (M3AAWG)

Bottom of last page in existing document sample. That's difficult to automate in Word generation, would rather it just be after all text.

**Comment by ronaldtse** [comment]
@opoudjis pure text is good enough. Thanks!

**Comment by opoudjis** [comment]
Actually, the real solution is to create a new section at the end of the document, and make it the footer for that section. I'll do that if I'm feeling adventurous.

**Comment by ronaldtse** [comment]
That's great. Whoever is publishing the document could manually do that anyway, so it's not critical. Thanks though!

**Comment by opoudjis** [comment]
The footer is on a new end page, that's the only way to get it to display, but I think that's acceptable.
